FROM postgres:14

ENV POSTGRES_USER=postgres
ENV POSTGRES_PASSWORD=1234
ENV POSTGRES_DB=investmedic

# Si tienes scripts de inicialización
COPY ./src/db/scripts/ /docker-entrypoint-initdb.d/

EXPOSE 5432