-- Deshabilitar restricciones de clave foránea temporalmente
SET session_replication_role = 'replica';

-- Borrar datos de las tablas en orden adecuado
TRUNCATE TABLE Failed_Login_Attempts RESTART IDENTITY CASCADE;
TRUNCATE TABLE Medical_Practitioner_Availability RESTART IDENTITY CASCADE;
TRUNCATE TABLE Prescription_Medication RESTART IDENTITY CASCADE;
TRUNCATE TABLE Prescription RESTART IDENTITY CASCADE;
TRUNCATE TABLE Audit_Log RESTART IDENTITY CASCADE;
TRUNCATE TABLE Feedback RESTART IDENTITY CASCADE;
TRUNCATE TABLE Obstetricians RESTART IDENTITY CASCADE;
TRUNCATE TABLE Consent RESTART IDENTITY CASCADE;
TRUNCATE TABLE Patient_Identification RESTART IDENTITY CASCADE;
TRUNCATE TABLE Identification_User RESTART IDENTITY CASCADE;
TRUNCATE TABLE Identification_Type RESTART IDENTITY CASCADE;
TRUNCATE TABLE Patient_Insurance RESTART IDENTITY CASCADE;
TRUNCATE TABLE Insurance RESTART IDENTITY CASCADE;
TRUNCATE TABLE Invoice_Details RESTART IDENTITY CASCADE;
TRUNCATE TABLE Invoice RESTART IDENTITY CASCADE;
TRUNCATE TABLE Payment RESTART IDENTITY CASCADE;
TRUNCATE TABLE Payment_Method RESTART IDENTITY CASCADE;
TRUNCATE TABLE Consult RESTART IDENTITY CASCADE;
TRUNCATE TABLE Appointment RESTART IDENTITY CASCADE;
TRUNCATE TABLE Status RESTART IDENTITY CASCADE;
TRUNCATE TABLE Medical_Practitioner_Service RESTART IDENTITY CASCADE;
TRUNCATE TABLE Service RESTART IDENTITY CASCADE;
TRUNCATE TABLE Medical_Practitioner_Specialty RESTART IDENTITY CASCADE;
TRUNCATE TABLE Specialty RESTART IDENTITY CASCADE;
TRUNCATE TABLE Medical_Practitioner RESTART IDENTITY CASCADE;
TRUNCATE TABLE Medical_History RESTART IDENTITY CASCADE;
TRUNCATE TABLE Patient RESTART IDENTITY CASCADE;
TRUNCATE TABLE User_Role RESTART IDENTITY CASCADE;
TRUNCATE TABLE Role RESTART IDENTITY CASCADE;
TRUNCATE TABLE "User" RESTART IDENTITY CASCADE;

-- Restaurar restricciones de clave foránea
SET session_replication_role = 'origin';
