name: Despliegue en EC2 con Docker

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código (Opcional, si necesitas copiar archivos a EC2)
        uses: actions/checkout@v4

      - name: Conectar a EC2 y desplegar
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            # Detener y eliminar contenedor anterior (si existe)
            docker stop ${{ secrets.CONTAINER_NAME }} || true
            docker rm ${{ secrets.CONTAINER_NAME }} || true

            # Pull de la nueva imagen desde Docker Hub
            docker pull ${{ secrets.DOCKER_REPO }}:latest

            # Ejecutar el nuevo contenedor
            docker run -d -p 80:80 --name ${{ secrets.CONTAINER_NAME }} ${{ secrets.DOCKER_REPO }}:latest

            # Opcional: Verificar el estado del contenedor
            docker ps

            # Opcional: Otros comandos que necesites ejecutar en EC2
            # Por ejemplo, copiar archivos, ejecutar scripts, etc.
